# Generated by Django 2.2.6 on 2019-10-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
    ]
